### ISSUE TITLE
Use Media

### ISSUE THREAD

**Issue by titoko** [newbthenewbd/grav-plugin-tinymce-editor#3] opened 2017-10-26 21:10 UTC
Hi, first just want to thank you for your great work on this !

The only thing I can't get to work is using the media system ?

How is it suppose to work ?
 
When I upload a img then I click on the "+" but it's a link popup wich appear,

I thinks it's a problem with the js include in the template file but before digging could you tell me if i'm doing everything the right way ?

Thanks

**Comment by newbthenewbd** [comment] 2017-10-27 01:28
Sounds about right, one is supposed to add an image with the use of the file picker, and then click the "+" next to it.

The JavaScript code that then executes basically tries to read the file as an image, if that fails - as an audio (that seemed to work well on videos in my tests, and browsers don't even seem to have a Video object in DOM), if even that gives an error - the file is just added as a hyperlink.

It'd be of great worth if I knew what browser You are using, and perhaps what the path to the file is. (i.e. /contact/phone.png)

**Comment by titoko** [comment] 2017-10-27 10:01
i'm using Firefox (latest version),

And when the link popup appear  it show => Avocats/IMG_20160801_180440.jpg

**Comment by newbthenewbd** [comment] 2017-10-28 01:34
Apparently, the issue seems to be caused by renaming a folder without the use of the admin plugin. When the admin plugin isn't used to do that, the cache isn't cleared, and the image goes 404. Saving the page should be all that's required to get everything working fine again. If it doesn't - clear Your website's cache from within the dashboard.

A less likely idea is that it might also be caused by some weird name conflicts, like starting the folder name with a capital letter, which doesn't seem to be the best practice according to the admin plugin - see how it blocks capital letters in the Folder Name section under Add Page.

That being said, I have an idea as to how this can be worked around so that even in such extreme cases the ~ugly file picker hack~ _advanced file type detector_ works right, so hopefully You can also wait for a patch to be released soon.

Thanks for reporting!

**Comment by newbthenewbd** [comment] 2017-10-28 02:15
Fixed in v1.1.1; due to how TinyMCE cooperates with Grav when the folder numeric prefix is used, the image still won't be properly visible in the editor until the page is saved, but will be added as an image rather than a link. You may submit a separate issue for that, if You want, but it's highly unlikely that it gets a patch soon.

**Closed by newbthenewbd** 2017-10-28 02:15 UTC
