### ISSUE TITLE
Image browse option not in grav-plugin-tinymce-editor

### ISSUE THREAD

**Issue by geogeorgejoseph** [newbthenewbd/grav-plugin-tinymce-editor#2] opened 2017-10-03 12:32 UTC
Can you possible to add Image browse option in this plugin ?

Currently in that insert image dialogue section have option to add the src , there is no option to browse the image file.

**Comment by newbthenewbd** [comment] 2017-10-03 16:37
Duplicate of #1; the feature is due to be added in v1.1.0 which hopefully gets released soon, as I already have the basic file picker integration code pretty much done locally, although its hackiness forces me to test it thoroughly first. If You need this "yesterday" and don't care about the inserting function doing nothing for now, You may implement the workaround found in #1 to get the file picker back.

**Closed by newbthenewbd** 2017-10-03 16:37 UTC
