### ISSUE TITLE
Call to a member function folder() on null"

### ISSUE THREAD

**Issue by eisidor** [newbthenewbd/grav-plugin-tinymce-editor#55] opened 2021-02-19 09:23 UTC
Call to a member function folder() on null"

<img width="407" alt="Screenshot 2021-02-19 at 11 18 51" src="https://user-images.githubusercontent.com/71765668/108484750-d34a5880-72a4-11eb-8f0a-1e939a325905.png">
<img width="818" alt="Screenshot 2021-02-19 at 11 18 55" src="https://user-images.githubusercontent.com/71765668/108484754-d5acb280-72a4-11eb-990f-ee3a98d45b5d.png">

**Comment by newbthenewbd** [comment] 2021-02-19 13:21
Looks like I am unable to trivially reproduce. Could you please share the steps that lead to the error?

Thanks!

**Comment by eisidor** [comment] 2021-02-24 20:22
> Looks like I am unable to trivially reproduce. Could you please share the steps that lead to the error?
> 
> Thanks!

when I try to save page in other language.  

I will back here with a screen record.

**Comment by eisidor** [comment] 2021-02-25 12:42
@newbthenewbd  here is a video https://streamable.com/k6gweb

**Comment by newbthenewbd** [comment] 2021-03-02 16:07
Yeah... weird. Finally managed to reproduce it with Flex Pages disabled, with a page of type Item placed in a Folder, and, as (un)expected, it seems that the essence of the issue is that `$page->getOriginal()` returns `null` in these (and similar?) circumstances. It might be a bug in Grav, but I'm not sure.

Had I noticed that the erroring place is actually only this deprecated thing for modifying the old-style absolute links, would have just pushed this workaround earlier, without trying to reproduce - anyways, fixed in v1.3.3, hopefully. :upside_down_face:

Thanks for reporting!

**Closed by newbthenewbd** 2021-03-02 16:07 UTC
