### ISSUE TITLE
Not loading images when inserting from page media

### ISSUE THREAD

**Issue by webandrew** [newbthenewbd/grav-plugin-tinymce-editor#7] opened 2017-12-08 13:25 UTC
After uploading a new image to page media, when using the **insert** option, I get a popup and all, but then the image doesn't appear in the tinymce until I save the document.
Alternatively, I have to upload, save and then insert. Any way around this?

**Comment by newbthenewbd** [comment] 2017-12-08 13:30
This is a known issue (see #3) that is hardly possible to fix when caused by messed up directory names, although the frequency I'm reminded of it hints to me that there might be something else to it.

Are You perhaps only using the admin panel for modifying pages, and otherwise manually editing the files, or is there anything else that's highly specific to Your configuration in terms of page creation?

**Comment by webandrew** [comment] 2017-12-08 13:43
I'm only using the admin panel. Well, I'm preparing it. I'm looking into having some basic users being able to put up content. That's why TinyMCE is a lifesaver, since markdown is not an option. And problems with images would be quite unfortunate.
ps. There's nothing specific about my configuration. Standard install + couple of basic plugins

**Comment by webandrew** [comment] 2017-12-08 13:56
Actually, here's a screengrab of the problem:
https://www.useloom.com/share/b5fde3cbcd89435ab55c017f13d908bf

**Comment by webandrew** [comment] 2017-12-08 14:27
Ok, found the problem. It dies on filenames with a whitespace. I was just testing around the browsers and some other files started to work. I was using photos with whitespace in the name, and they weren't working. Can anything be done about that by any chance?

**Comment by newbthenewbd** [comment] 2017-12-08 14:31
Whitespace? Very interesting, as the original issue is caused by caches not being generated at a point. Perhaps I got the cache filename formatting somewhat wrong?

I'm trying to debug this myself right now, and will see what can be done. Thanks for reporting!

**Comment by newbthenewbd** [comment] 2017-12-08 14:37
Actually, what browser are You using if I may ask? This might be ugly-Javascript-bugs-specific...

**Comment by webandrew** [comment] 2017-12-08 14:49
I've been having problems on Chrome. Started working on Edge, but since then I've noticed it was because of the whitespace, not the browser. Works fine on files without on both.

**Comment by webandrew** [comment] 2017-12-08 14:52
Here, you can see me trying to use an image with and without whitespace:
https://www.useloom.com/share/221feba751ad4addb37258331a149ab8

**Comment by newbthenewbd** [comment] 2017-12-08 15:15
Hrm, it's working fine for me. Maybe it's ~Windows~ encoding-specific? Quite sure not an easy thing to debug.

Could You verify that a file affected by this exists in the appropriate directory under `user/pages` before the page is saved and has the right name? For me, it does, and if it doesn't, that bug is bound to happen, but I'm unable to figure out what exactly makes it only appear after the save when whitespaces are used, aside from page renames...

**Comment by webandrew** [comment] 2017-12-08 15:30
Both files are uploading correctly into the folder. And I'm not even touching page names.

Now, hope you won't hate me for this, but the problem dissipated. Don't know how. Stuff is working now, for no reason. Sorry for dragging you into this :)

**Comment by newbthenewbd** [comment] 2017-12-08 15:34
Huh, interesting. That only proves that the bug is an ugly one, though, and not that it doesn't exist. The path to the page that You've been testing on was always same, right?

**Comment by webandrew** [comment] 2017-12-08 15:43
Yeah, I know. It's probably a conjunction with some other js event or error or something. Yes it is \pages\03.test in terms of directory.

**Comment by webandrew** [comment] 2017-12-08 15:47
This thing pops up sometimes on me. Maybe it has an effect on it? Unfortunately it's a .min.js so readability is not great

![image](https://user-images.githubusercontent.com/6526824/33773121-c685a5e2-dc2e-11e7-8007-85c38a4f8d46.png)

**Comment by webandrew** [comment] 2017-12-08 15:49
Nope, wait.... found the error source. It's hovering over the View
![image](https://user-images.githubusercontent.com/6526824/33773324-67c5c464-dc2f-11e7-8d97-cc9ec8793805.png)

**Comment by newbthenewbd** [comment] 2021-01-09 07:34
The architecture of the plugin has changed a lot since the submission of the issue. Should the problem still arise in v1.3.0 or newer, please notify - for now, closing.

Thank You!

**Closed by newbthenewbd** 2021-01-09 07:34 UTC

**Comment by aasampaio** [comment] 2024-09-02 11:06
Hi @newbthenewbd 
Using TinyMCE Editor Integration v1.3.3 (Grav v1.7.46 - Admin v1.10.46 ) and getting the same issue.
Images don't show on the backend but show on the published page (frontend).
No errors on Grav log.
